### ISSUE TITLE
Quality of pretrained model

### ISSUE THREAD

**Issue by wojtat** [viplix3/PointPillars-TF#5]
Hello,
I was trying to recreate the results you had advertised in the demo_imgs folder in the repository. I tried to run inference with the model that you provided a link for in the #2 issue.
At first, this didn't load properly in the master branch version. I eventually resorted to adding the anchor box for cyclists from the cyclist branch to the master branch and that worked.
However, the results that can be seen in the demo_imgs folder are much better than the results I was able to reproduce. I got only a handful of detections.

So I basically have 2 questions:
1) Is it correct to simply add the cyclist anchor boxes from the cyclist branch to the master branch, or do I need to do something else as well?
2) How did you run the inference such that you got the results you got?

Thanks in advance!

**Comment by viplix3** [comment]
Hi @wojtat, apologies for the delayed response.
I am not maintaining this repository anymore so I didn't check the issues page.

Ques: Is it correct to simply add the cyclist anchor boxes from the cyclist branch to the master branch, or do I need to do something else as well?
Yes, it is correct, however, the weights shared in issue #2 might be of some older variant of the repo but unfortunately, I didn't keep track of the model weight files at that time so I cannot comment for sure.

Ques: How did you run the inference such that you got the results you got?
To generate the shared results I simply trained the model using the provided code on KITTI dataset (data split used provided in image_sets folder)

Unfortunately, I don't have access to the weights used to produce the shared results anymore.


I'll keep the issue open for now and would try training a model for a few epochs (if you are still working on this).
I will share the updated weights with you accordingly.

**Comment by wojtat** [comment]
Hi @viplix3,

thank you for your reply!

I have tried inference with the partially trained model you provided. It already works much better than when I tried to train a model on my own. I think I must be doing something wrong when I train. Would it be possible for you to train the model fully? If so, I would really appreciate it.

Thanks again for your help.

**Comment by viplix3** [comment]
@wojtat unfortunately I don't have enough resources to train a model.
I have a single GPU in which I can only fit a batch size of 3 for training.

My current workplace tasks are keeping me busy and it isn't possible for me to update the codebase to handle subdivisions.
Sorry, but it wouldn't be possible for me to train a model at the moment.
